"""Add hashed email

Revision ID: 7413921a853c
Revises: d26f7b76427d
Create Date: 2025-02-22 16:22:52.830054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7413921a853c'
down_revision: Union[str, None] = 'd26f7b76427d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_hashed', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email_hashed'), 'users', ['email_hashed'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_hashed'), table_name='users')
    op.drop_column('users', 'email_hashed')
    # ### end Alembic commands ###
