"""empty message

Revision ID: 92519c30be2c
Revises: 7413921a853c
Create Date: 2025-02-24 10:46:07.444028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92519c30be2c'
down_revision: Union[str, None] = '7413921a853c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_hashed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_email_hashed', table_name='users')
    op.create_unique_constraint(None, 'users', ['email_hashed'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email_hashed', 'users', ['email_hashed'], unique=True)
    op.alter_column('users', 'email_hashed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
