"""update user model

Revision ID: e1786f59ca12
Revises: ebedd69b6fa7
Create Date: 2025-01-25 15:12:46.792865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1786f59ca12'
down_revision: Union[str, None] = 'ebedd69b6fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.String(), nullable=False))
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('pronunciation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('job', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pronouns', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('social_accounts', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('emails', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('phone_numbers', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.JSON(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['uid'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'isVerified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isVerified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'interests')
    op.drop_column('users', 'phone_numbers')
    op.drop_column('users', 'emails')
    op.drop_column('users', 'social_accounts')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'pronouns')
    op.drop_column('users', 'job')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'pronunciation')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###
